import 'package:get/get_navigation/src/root/internacionalization.dart';

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'uz_UZ': {
          'password_invalid':
              "Parolning uzunligi eng kamida \n8 ta belgidan iborat bo'lishi shart!",
          'email_not_valid': 'Elektron pochta xato kiritildi!',
          'referall_not_valid': 'Referallni kiritish lozim!',
          'name_not_valid': "Ismda eng kamida 4 ta \nbelgi bo'lishi lozim",
          'sign_up': "Ro'yxatdan o'tish",
          'login': 'Kirish',
          '': 'Login to your account',
          'do_not_have_an_account': "Shaxsiy hisobingiz yo'qmi?",
          'email': 'Elektron pochta',
          'password': "Maxfiy so'z",
          'create_account': 'Shaxsiy hisob oching, bu tekin ;) ',
          'login_to_your_account': 'Shaxsiy hisobga kirish',
          'name': 'Ism',
          'surname': 'Familiya',
          'Already have an account?': 'Allaqachon shaxsiy hisobingiz bormi? ',
          'Login': 'Kirish',
          'product count:' : 'Tovar soni',
          'sum':"Xizmat to'lovi:",
          'all':'Barchasi',
          'mine':'Mening',
          'referals': 'Referallar',
          'done': 'Yakunlangan',
          'created': 'Yaratilgan',
          'cancelled':'Rad etilgan',
          'progress': 'Jarayonda'

        },
        'en_En': {
          'password_invalid':
              'The password must contain at least \n8 characters!',
          'email_not_valid': 'E-mail entered incorrectly!',
          'referall_not_valid': 'You need to enter your referall!',
          'name_not_valid': 'Name must contain at \nleast 4 characters',
          'sign_up': 'Sign Up',
          'login': 'Login',
          'do_not_have_an_account': "Don't have an account?",
          'email': 'Email',
          'password': 'Password',
          'create_account': "Create an account, It's free ",
          'login_to_your_account': 'Login to your account',
          'name': 'Name',
          'surname': 'Surname',
          'product count:' : 'Product count:',
          'sum':'Service price:',
          'all':'All',
          'mine':'My',
          'referals': 'Referrals',
          'done': 'Done',
          'created': 'Created',
          'cancelled':'Cancelled',
          'progress': 'Progress',
          'choose_market': "Do'konni tanlash",
          'choose_dates': 'Sanalarni tanlash',
          'count_of_products': 'Mahsulotlar soni:',
          'delivery_note': 'Yukxat',
          'count': 'Soni',
          'choose_photo': 'Rasm tanlash',
          'add': "Qo'shish",
          'you_must_select_market': "Do'kon tanlanmadi!",
          'you_must_select_data': 'Eng kamida bitta sana\ntanlanishi kerak!',
          'you_must_add_product':
              'Eng kamida bitta mahsulot\ntanlanishi kerak!',
          'you_must_select_photo': 'Rasm yuklanishi shart!',
          'products': 'Mahsulotlar:',
          'order': 'Rasmiylashtirish',
          'ordered_successfully': 'Buyurtma rasmiylashtirildi!',
          'you_need_to_create_market':
              "Do'kon qo'shgach buyurtma\nqila olasiz.",
          'try_again': "Qayta urinib ko'ring",
          'create_order': 'Buyurtma rasmiylashtirish',
        },
        'ru_Ru': {
          'password_invalid': 'Пароль должен содержать не менее \n8 символов!',
          'email_not_valid': 'E-mail введен неверно!',
          'referall_not_valid': 'Вам необходимо ввести\nсвою рефераль!',
          'name_not_valid': 'Имя должно содержать не менее \n4 символов.',
          'sign_up': 'Зарегистрироваться',
          'login': 'Авторизоваться',
          'do_not_have_an_account': 'У вас нет учетной записи?',
          'email': 'Электронная почта',
          'password': 'Пароль',
          'create_account': 'Создайте учетную запись, это бесплатно',
          'login_to_your_account': 'Войдите в свой аккаунт',
          'name': 'Имя',
          'surname': 'Фамилия',
          'choose_market': 'Выберите магазин',
          'choose_dates': 'Выберите даты',
          'count_of_products': 'Количество продуктов:',
          'delivery_note': 'Накладная',
          'count': 'Количество',
          'choose_photo': 'Выберите изображениеh',
          'add': 'Добавлять',
          'order': 'Формализация',
          'you_must_select_market': 'Магазин не выбран!',
          'you_must_select_data': 'Необходимо ввести хотя\nбы одну дату!',
          'you_must_add_product': 'Должен быть хотя бы один товар!',
          'you_must_select_photo': 'Изображение должно\nбыть загружено!',
          'products': 'Продукты:',
          'ordered_successfully': 'Заказ выполнен!',
          'you_need_to_create_market':
          'Оформить заказ можно после\nдобавления магазина.',
          'try_again': 'Попробуйте еще раз',
          'create_order': 'Сделать заказ',
          'product count:' : 'Количество продуктов:',
          'sum':'Цена услуги:',
          'all':'Все',
          'mine':'Мой',
          'referals': 'Рефералы',
          'done': 'Сделанный',
          'created': 'Созданный',
          'cancelled':'Отменено',
          'progress': 'Прогресс'

        }
      };
}
