name: time_slot
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 2.0.17

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: ^2.20.0
  animated_snack_bar: ^0.3.1
  flutter_bloc: ^8.1.3
  flutter_screenutil: ^5.9.0
  adaptive_theme: ^3.4.0
  get: ^4.6.6
  get_it: ^7.6.4
  email_validator: ^2.1.17
  equatable: ^2.0.5
  zoom_tap_animation: ^1.1.0
  firebase_auth: ^4.10.0
  cloud_firestore: ^4.9.2
  image_picker: ^1.0.4
  carousel_slider: ^4.2.1
  shimmer: ^3.0.0
  cached_network_image: ^3.3.0
  lottie: ^2.3.2
  firebase_storage: ^11.2.7
  firebase_app_check: ^0.2.0
  flutter_svg: ^2.0.7
  intl: ^0.18.1
  url_launcher: ^6.1.14
  share_plus: ^7.2.1
  easy_image_viewer: ^1.2.1
  in_app_update: ^4.2.2
  google_sign_in: ^6.1.5
  appinio_video_player: ^1.2.2
  webview_flutter: ^4.4.1
  webview_flutter_android: ^3.12.0
  path_provider: ^2.1.1
  webview_flutter_wkwebview: ^3.9.1
  hive: ^2.2.3
  firebase_messaging: ^14.7.1
  flutter_local_notifications: ^15.1.1
  scrollable_clean_calendar: ^1.4.1
  dio: ^5.3.3
  flutter_phone_direct_caller: ^2.1.1
  permission_handler: ^11.0.1
  fluttertoast: ^8.2.2
  feature_discovery: ^0.14.1
  flutter_launcher_icons: ^0.13.1
  awesome_ripple_animation: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/sp_logo.png"


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/lottie/
    - assets/icons/

